import { useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router'
import { useForm, useWatch } from 'react-hook-form'
import { useMutation, useQuery } from '@tanstack/react-query'
import { z } from 'zod'
import { ApiError } from '../../shared/api/http'
import * as api from './api'
import { base, scope, title, time, usePage, useRefresh, type Role } from './hooks'
import { Heading, ErrorBox, Pagination, Confirmation } from './ui'
export function BookingCreate({ token }: { token: string }) {
  const { id = '' } = useParams(); const navigate = useNavigate(); const refresh = useRefresh()
  const property = useQuery({ queryKey: ['operations', 'published-property', id], queryFn: ({ signal }) => api.property(id, signal) })
  const [quote, setQuote] = useState<api.Quote | null>(null); const [message, setMessage] = useState(''); const [confirm, setConfirm] = useState(false)
  const attempt = useRef<{ payload: string; key: string } | null>(null)
  const { register, handleSubmit, control, formState: { isSubmitting } } = useForm<z.infer<typeof api.staySchema>>({ defaultValues: { checkIn: api.today(), checkOut: api.addDays(api.today(), 1), guestCount: 1 } })
  const current = useWatch({ control }); const sameQuote = quote && quote.propertyId === Number(id) && quote.checkIn === current.checkIn && quote.checkOut === current.checkOut && quote.guestCount === current.guestCount
  const availability = useMutation({ mutationFn: (input: z.infer<typeof api.staySchema>) => api.availability(token, Number(id), input) })
  const booking = useMutation({ mutationFn: ({ value, key }: { value: api.Quote; key: string }) => api.reserve(token, value, key) })
  async function check(input: z.infer<typeof api.staySchema>) {
    setMessage(''); setQuote(null); setConfirm(false)
    const parsed = api.staySchema.safeParse(input)
    if (!parsed.success) { setMessage(parsed.error.issues[0].message); return }
    if (parsed.data.guestCount > (property.data?.capacity ?? 0)) { setMessage('El número de huéspedes supera la capacidad del alojamiento.'); return }
    try { setQuote(await availability.mutateAsync(parsed.data)) } catch (error) { setMessage(error instanceof Error ? error.message : 'No pudimos consultar las fechas.') }
  }
  async function reserve() {
    if (!quote || !sameQuote || booking.isPending) return
    const payload = JSON.stringify(quote)
    if (!attempt.current || attempt.current.payload !== payload) attempt.current = { payload, key: crypto.randomUUID() }
    setMessage('')
    try { const saved = await booking.mutateAsync({ value: quote, key: attempt.current.key }); await refresh(); navigate(`/guest/bookings/${saved.id}`, { replace: true, state: { registered: true } }) } catch (error) { if (error instanceof ApiError && error.status === 409) { setQuote(null); setConfirm(false); void property.refetch() } setMessage(error instanceof Error ? error.message : 'No pudimos registrar la reserva.') }
  }
  if (property.isPending) return <p role="status">Cargando alojamiento…</p>
  if (property.isError) return <ErrorBox error={property.error} retry={() => void property.refetch()} />
  const p = property.data
  return <><Heading text={p.title} note={`${p.district}, ${p.city} · Hasta ${p.capacity} huéspedes`} /><div className="ops-two-columns"><section className="ops-panel"><h2>Información del alojamiento</h2><p className="ops-description">{p.description}</p><dl className="ops-details"><div><dt>Dirección</dt><dd>{p.address}</dd></div><div><dt>Habitaciones / camas / baños</dt><dd>{p.bedrooms} / {p.beds} / {p.bathrooms}</dd></div><div><dt>Tarifa por noche</dt><dd>{api.money(p.nightlyRate, p.currency)}</dd></div></dl></section><section className="ops-panel"><h2>Consulta disponibilidad</h2><p>La fecha de salida no ocupa una noche. Máximo 366 noches por estadía.</p><form className="ops-form" noValidate onSubmit={handleSubmit(check)}><fieldset disabled={isSubmitting || booking.isPending}><label>Llegada<input type="date" min={api.today()} {...register('checkIn')} /></label><label>Salida<input type="date" min={current.checkIn} {...register('checkOut')} /></label><label>Huéspedes<input type="number" min="1" max={p.capacity} {...register('guestCount', { valueAsNumber: true })} /></label><button className="ops-primary">{isSubmitting ? 'Consultando…' : 'Consultar disponibilidad'}</button></fieldset></form>{quote && sameQuote && <div className={quote.available ? 'ops-success' : 'ops-error'} role="status">{quote.available ? <><strong>Fechas disponibles</strong><p>{quote.nights} noches · Total: {api.money(quote.totalAmount, quote.currency)}</p><p>La disponibilidad se comprueba otra vez al registrar.</p></> : <p>Estas fechas están ocupadas o bloqueadas. Elige otro rango.</p>}</div>}{quote?.available && sameQuote && !confirm && <button className="ops-primary" onClick={() => setConfirm(true)}>Solicitar reserva</button>}{confirm && quote && sameQuote && <Confirmation label="Confirmar reserva" busy={booking.isPending} cancel={() => setConfirm(false)}><h3>Confirmar tu estadía</h3><p>{quote.checkIn} → {quote.checkOut} · {quote.guestCount} huéspedes</p><p>Total registrado: {api.money(quote.totalAmount, quote.currency)}. El pago se registra después y será simulado.</p><div className="ops-actions"><button disabled={booking.isPending} onClick={() => setConfirm(false)}>Cancelar</button><button className="ops-primary" disabled={booking.isPending} onClick={() => void reserve()}>{booking.isPending ? 'Registrando…' : 'Confirmar reserva'}</button></div></Confirmation>}{!sameQuote && quote && <p>Consulta nuevamente las fechas modificadas.</p>}{message && <p className="ops-error" role="alert">{message}</p>}</section></div></>
}

export function BookingList({ token, role }: { token: string; role: Role }) {
  const { page, change } = usePage()
  const query = useQuery({ queryKey: ['operations', role, token, 'bookings', page], queryFn: ({ signal }) => api.bookings(token, scope(role), page, signal) })
  return <><Heading text={title(role)} note="Consulta fechas, importes y estados registrados en la plataforma." /><button disabled={query.isFetching} onClick={() => void query.refetch()}>Actualizar reservas</button>{query.isPending ? <p role="status">Consultando reservas…</p> : query.isError ? <ErrorBox error={query.error} retry={() => void query.refetch()} /> : <><p>{query.data.total} reservas registradas</p>{query.data.items.length === 0 && <section className="ops-panel"><h2>No hay reservas en esta página</h2><p>Las reservas registradas aparecerán aquí.</p>{page > 0 && <button onClick={() => change(0)}>Ir a la primera página</button>}{role === 'GUEST' && <Link to="/guest">Explorar alojamientos</Link>}</section>}<div className="ops-grid">{query.data.items.map(b => <article className="ops-panel" key={b.id}><span className={`ops-status ops-status-${b.status.toLowerCase()}`}>{api.bookingLabels[b.status]}</span><h2>{b.propertyTitle}</h2><p>{b.district} · {b.checkIn} → {b.checkOut}</p><p>{b.guestCount} huéspedes · {api.money(b.totalAmount, b.currency)}</p>{role !== 'GUEST' && <p>Huésped: {b.guest.name}</p>}<p>Pago: {b.payment ? api.paymentLabels[b.payment.status] : 'No registrado'}</p><Link to={`${base(role)}/bookings/${b.id}`}>Ver reserva #{b.id} →</Link></article>)}</div><Pagination page={page} pages={query.data.pages} change={change} busy={query.isFetching} /></>}</>
}
export function BookingDetail({ token, role }: { token: string; role: Role }) {
  const { id = '' } = useParams()
  const query = useQuery({ queryKey: ['operations', role, token, 'booking', id], queryFn: ({ signal }) => api.booking(token, scope(role), id, signal), refetchOnWindowFocus: false })
  if (query.isPending) return <p role="status">Consultando reserva…</p>
  if (query.isError) return <ErrorBox error={query.error} retry={() => void query.refetch()} />
  const b = query.data
  return <><Heading text={`Reserva #${b.id}`} note={b.propertyTitle} /><section className="ops-panel"><span className={`ops-status ops-status-${b.status.toLowerCase()}`}>{api.bookingLabels[b.status]}</span><h2>Reserva registrada</h2><p className="ops-confirmation-code">Confirmación: {b.confirmationCode}</p><dl className="ops-details"><div><dt>Fechas</dt><dd>{b.checkIn} → {b.checkOut}</dd></div><div><dt>Huéspedes</dt><dd>{b.guestCount}</dd></div><div><dt>Tarifa aplicada</dt><dd>{api.money(b.nightlyRate, b.currency)} / noche</dd></div><div><dt>Total registrado</dt><dd>{api.money(b.totalAmount, b.currency)}</dd></div><div><dt>Registrada</dt><dd>{time(b.confirmedAt)}</dd></div><div><dt>Huésped</dt><dd>{b.guest.name} · {b.guest.email}</dd></div><div><dt>Anfitrión</dt><dd>{b.host.name} · {b.host.email}</dd></div></dl><button disabled={query.isFetching} onClick={() => void query.refetch()}>Actualizar reserva y pago</button><p><Link to={`${base(role)}/bookings`}>Volver a las reservas</Link></p></section><section className="ops-panel"><h2>Pago simulado</h2>{b.payment ? <><p className="ops-success">{api.paymentLabels[b.payment.status]} · {api.money(b.payment.amount, b.payment.currency)}</p><p>Referencia: <span className="ops-confirmation-code">{b.payment.reference}</span></p><p>Registrado: {time(b.payment.processedAt)}</p></> : <p>No se ha registrado un pago para esta reserva.</p>}{role === 'GUEST' && !b.payment && (b.status === 'CONFIRMED' || b.status === 'IN_PROGRESS') && <PaymentAction key={`${b.id}-${b.version}`} token={token} booking={b} />}{b.status === 'CANCELLED' && b.payment && <p>La cancelación conserva el pago simulado registrado. No se procesa un reembolso bancario.</p>}</section>{role === 'ADMINISTRATOR' && <><StatusAction key={`${b.id}-${b.version}`} token={token} booking={b} /><BookingHistory token={token} id={b.id} version={b.version} /></>}</>
}
function PaymentAction({ token, booking }: { token: string; booking: api.Booking }) {
  const [open, setOpen] = useState(false); const [error, setError] = useState(''); const refresh = useRefresh()
  const mutation = useMutation({ mutationFn: () => api.pay(token, booking) })
  async function pay() { setError(''); try { await mutation.mutateAsync(); await refresh() } catch (error) { setError(error instanceof Error ? error.message : 'No pudimos registrar el pago.') } }
  return <>{!open ? <button className="ops-primary" onClick={() => setOpen(true)}>Registrar pago simulado</button> : <Confirmation label="Confirmar pago simulado" busy={mutation.isPending} cancel={() => setOpen(false)}><h3>Confirmar pago de demostración</h3><p>Se registrarán {api.money(booking.totalAmount, booking.currency)} como pago aprobado simulado. No se cobrará dinero ni se solicitarán datos bancarios.</p><div className="ops-actions"><button disabled={mutation.isPending} onClick={() => setOpen(false)}>Cancelar</button><button className="ops-primary" disabled={mutation.isPending} onClick={() => void pay()}>{mutation.isPending ? 'Registrando pago…' : 'Confirmar pago simulado'}</button></div></Confirmation>}{error && <p className="ops-error" role="alert">{error}</p>}</>
}
const transitions: Record<api.BookingStatus, api.BookingStatus[]> = { CONFIRMED: ['IN_PROGRESS', 'CANCELLED'], IN_PROGRESS: ['COMPLETED', 'CANCELLED'], COMPLETED: [], CANCELLED: [] }
function StatusAction({ token, booking }: { token: string; booking: api.Booking }) {
  const [selected, setSelected] = useState<api.BookingStatus | ''>(''); const [confirm, setConfirm] = useState(false); const [error, setError] = useState(''); const [comment, setComment] = useState(''); const refresh = useRefresh()
  const mutation = useMutation({ mutationFn: (status: api.BookingStatus) => api.changeStatus(token, booking, status, comment.trim()) })
  async function save() { if (!selected || !comment.trim()) { setError('Indica el motivo del cambio de estado.'); return } setError(''); try { await mutation.mutateAsync(selected); await refresh() } catch (error) { setError(error instanceof Error ? error.message : 'No pudimos actualizar la reserva.') } }
  return <section className="ops-panel"><h2>Seguimiento administrativo</h2>{transitions[booking.status].length ? <><label className="ops-label">Nuevo estado<select value={selected} disabled={mutation.isPending} onChange={event => { const value = transitions[booking.status].find(v => v === event.target.value); setSelected(value ?? ''); setConfirm(false) }}><option value="">Selecciona un estado</option>{transitions[booking.status].map(status => <option key={status} value={status}>{api.bookingLabels[status]}</option>)}</select></label><button disabled={!selected || mutation.isPending} onClick={() => setConfirm(true)}>Revisar cambio</button>{confirm && selected && <Confirmation label="Confirmar cambio de estado" busy={mutation.isPending} cancel={() => setConfirm(false)}><p>{api.bookingLabels[booking.status]} → {api.bookingLabels[selected]}</p>{selected === 'CANCELLED' && <p>Cancelar libera las fechas y conserva el historial y cualquier pago simulado.</p>}<label className="ops-label">Motivo del cambio<textarea maxLength={1000} value={comment} disabled={mutation.isPending} onChange={event => setComment(event.target.value)} /></label><div className="ops-actions"><button disabled={mutation.isPending} onClick={() => setConfirm(false)}>Cancelar cambio</button><button className="ops-primary" disabled={mutation.isPending} onClick={() => void save()}>{mutation.isPending ? 'Guardando…' : 'Confirmar cambio de estado'}</button></div></Confirmation>}</> : <p>Esta reserva está en un estado final y no admite más cambios.</p>}{error && <p className="ops-error" role="alert">{error}</p>}</section>
}
function BookingHistory({ token, id, version }: { token: string; id: number; version: number }) {
  const query = useQuery({ queryKey: ['operations', 'history', token, id, version], queryFn: ({ signal }) => api.history(token, id, signal) })
  return <section className="ops-panel"><h2>Historial de estados</h2>{query.isPending ? <p role="status">Consultando historial…</p> : query.isError ? <ErrorBox error={query.error} retry={() => void query.refetch()} /> : <ul className="ops-timeline">{query.data.map((item, i) => <li key={`${item.changedAt}-${i}`}><strong>{api.bookingLabels[item.newStatus]}</strong><p>{time(item.changedAt)} · {item.comment}</p></li>)}</ul>}</section>
}

