import { useState } from 'react'
import { useParams } from 'react-router'
import { useForm } from 'react-hook-form'
import { useMutation, useQuery } from '@tanstack/react-query'
import { z } from 'zod'
import { useSession } from '../auth/session'
import * as api from './api'
import { scope, useRefresh, type Role } from './hooks'
import { Heading, ErrorBox, Confirmation } from './ui'
export function Calendar({ token, role }: { token: string; role: Role }) {
  const { id = '' } = useParams(); const session = useSession(); const refresh = useRefresh(); const [range, setRange] = useState({ startDate: api.today(), endDate: api.addDays(api.today(), 30) }); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [selected, setSelected] = useState<api.Block | null>(null)
  const { register, handleSubmit } = useForm({ defaultValues: range })
  const query = useQuery({ queryKey: ['operations', role, token, 'calendar', id, range], queryFn: ({ signal }) => api.calendar(token, scope(role), id, range, signal) })
  const release = useMutation({ mutationFn: (block: api.Block) => api.deactivate(token, scope(role), block) })
  async function deactivate() { if (!selected) return; setError(''); try { await release.mutateAsync(selected); setSelected(null); setNotice('Bloqueo desactivado. Las fechas se recalcularon.'); await refresh() } catch (error) { setError(error instanceof Error ? error.message : 'No pudimos desactivar el bloqueo.') } }
  return <><Heading text={`Disponibilidad de propiedad #${id}`} note="Inicio incluido, fin excluido. Las reservas canceladas no ocupan fechas." /><section className="ops-panel"><h2>Consultar calendario de fechas</h2><form className="ops-form ops-inline" noValidate onSubmit={handleSubmit(values => { const parsed = api.dateRangeSchema.safeParse(values); if (!parsed.success) { setError(parsed.error.issues[0].message); return } setError(''); setSelected(null); setRange(parsed.data) })}><label>Desde<input type="date" {...register('startDate')} /></label><label>Hasta (excluido)<input type="date" {...register('endDate')} /></label><button className="ops-primary">Consultar calendario</button></form><button disabled={query.isFetching} onClick={() => void query.refetch()}>Actualizar fechas</button>{notice && <p className="ops-success" role="status">{notice}</p>}{error && <p className="ops-error" role="alert">{error}</p>}{query.isPending ? <p role="status">Consultando fechas…</p> : query.isError ? <ErrorBox error={query.error} retry={() => void query.refetch()} /> : <><h3>Estadías registradas</h3>{!query.data.reservations.length && <p>No hay estadías que ocupen este rango.</p>}<ul className="ops-timeline">{query.data.reservations.map((value, i) => <li key={`${value.startDate}-${i}`}>{value.startDate} → {value.endDate} · Reservada</li>)}</ul><h3>Bloqueos</h3>{!query.data.blocks.length && <p>No hay bloqueos en este rango.</p>}<ul className="ops-timeline">{query.data.blocks.map(block => <li key={block.id}><strong>{block.startDate} → {block.endDate}</strong><p>{block.reason} · {block.active ? 'Activo' : 'Desactivado'}</p>{block.active && (role === 'ADMINISTRATOR' || block.createdById === session?.user.id) && <button disabled={release.isPending} onClick={() => setSelected(block)}>Desactivar bloqueo #{block.id}</button>}{block.active && role === 'HOST' && block.createdById !== session?.user.id && <p>Bloqueo administrativo: solo el administrador puede retirarlo.</p>}</li>)}</ul>{selected && <Confirmation label="Confirmar desactivación de bloqueo" busy={release.isPending} cancel={() => setSelected(null)}><h3>Desactivar bloqueo</h3><p>{selected.startDate} → {selected.endDate} · {selected.reason}</p><p>Se conservará el historial del bloqueo y sus fechas podrán volver a reservarse.</p><div className="ops-actions"><button disabled={release.isPending} onClick={() => setSelected(null)}>Cancelar</button><button className="ops-primary" disabled={release.isPending} onClick={() => void deactivate()}>{release.isPending ? 'Guardando…' : 'Confirmar desactivación'}</button></div></Confirmation>}</>}</section>{query.isSuccess && <BlockForm token={token} role={role} id={id} saved={value => { setNotice(`Bloqueo registrado: ${value.startDate} → ${value.endDate}.`); void refresh() }} />}</>
}
const blockFormSchema = z.object({ startDate: z.iso.date(), endDate: z.iso.date(), reason: z.string().trim().min(1, 'Indica el motivo del bloqueo.').max(255) }).refine(value => value.startDate >= api.today() && value.endDate > value.startDate && (Date.parse(value.endDate) - Date.parse(value.startDate)) / 86400000 <= 366, { message: 'Elige fechas desde hoy, con fin posterior y hasta 366 días.', path: ['endDate'] })
function BlockForm({ token, role, id, saved }: { token: string; role: Role; id: string; saved: (block: api.Block) => void }) {
  const [error, setError] = useState(''); const [confirm, setConfirm] = useState<z.infer<typeof blockFormSchema> | null>(null)
  const { register, handleSubmit, reset } = useForm<z.infer<typeof blockFormSchema>>({ defaultValues: { startDate: api.today(), endDate: api.addDays(api.today(), 1), reason: '' } })
  const mutation = useMutation({ mutationFn: (values: z.infer<typeof blockFormSchema>) => api.block(token, scope(role), id, values) })
  async function submit() { if (!confirm || mutation.isPending) return; setError(''); try { const block = await mutation.mutateAsync(confirm); saved(block); setConfirm(null); reset() } catch (error) { setError(error instanceof Error ? error.message : 'No pudimos registrar el bloqueo.') } }
  return <section className="ops-panel"><h2>Bloquear fechas</h2><p>No se permite bloquear rangos que crucen reservas o bloqueos activos.</p><form className="ops-form" noValidate onSubmit={handleSubmit(values => { const parsed = blockFormSchema.safeParse(values); if (!parsed.success) { setError(parsed.error.issues[0].message); return } setError(''); setConfirm(parsed.data) })}><fieldset disabled={mutation.isPending || Boolean(confirm)}><label>Inicio del bloqueo<input type="date" min={api.today()} {...register('startDate')} /></label><label>Fin del bloqueo (excluido)<input type="date" {...register('endDate')} /></label><label>Motivo del bloqueo<input maxLength={255} {...register('reason')} /></label><button className="ops-primary">Revisar bloqueo</button></fieldset></form>{confirm && <Confirmation label="Confirmar bloqueo de fechas" busy={mutation.isPending} cancel={() => setConfirm(null)}><p>{confirm.startDate} → {confirm.endDate} · {confirm.reason}</p><div className="ops-actions"><button disabled={mutation.isPending} onClick={() => setConfirm(null)}>Cancelar bloqueo</button><button className="ops-primary" disabled={mutation.isPending} onClick={() => void submit()}>{mutation.isPending ? 'Guardando…' : 'Confirmar bloqueo'}</button></div></Confirmation>}{error && <p className="ops-error" role="alert">{error}</p>}</section>
}

