import { Link } from 'react-router'
import { useQuery } from '@tanstack/react-query'
import * as api from './api'
import { statusLabels } from '../properties/schemas'
import { base, scope, usePage, useRefresh, type Role } from './hooks'
import { Heading, ErrorBox, Pagination } from './ui'
export function Overview({ token, role }: { token: string; role: Role }) {
  const { page, change } = usePage(); const refresh = useRefresh()
  const summary = useQuery({ queryKey: ['operations', role, token, 'summary'], queryFn: ({ signal }) => api.summary(token, scope(role), signal) })
  const properties = useQuery({ queryKey: ['operations', role, token, 'properties', page], queryFn: ({ signal }) => api.managedProperties(token, scope(role), page, signal) })
  return <><Heading text={role === 'HOST' ? 'Resumen de mis alojamientos' : 'Indicadores de operación'} note="Información agregada de propiedades, reservas y pagos registrados." /><button disabled={summary.isFetching || properties.isFetching} onClick={() => void refresh()}>Actualizar resumen</button>{summary.isPending ? <p role="status">Consultando indicadores…</p> : summary.isError ? <ErrorBox error={summary.error} retry={() => void summary.refetch()} /> : <><div className="ops-stats">{[['Propiedades', summary.data.properties], ['Reservas', summary.data.bookings], ['Próximas llegadas', summary.data.upcomingBookings], ['Bloqueos activos', summary.data.activeBlocks], ['Pagos simulados', summary.data.payments]].map(([label, value]) => <article className="ops-panel" key={String(label)}><h2>{label}</h2><strong>{value}</strong></article>)}</div><div className="ops-two-columns"><section className="ops-panel"><h2>Estados de propiedades</h2><dl className="ops-details">{Object.entries(statusLabels).map(([code, label]) => <div key={code}><dt>{label}</dt><dd>{summary.data.propertiesByStatus[code] ?? 0}</dd></div>)}</dl><h3>Estados de reservas</h3><dl className="ops-details">{Object.entries(api.bookingLabels).map(([code, label]) => <div key={code}><dt>{label}</dt><dd>{summary.data.bookingsByStatus[code] ?? 0}</dd></div>)}</dl></section><section className="ops-panel"><h2>Importes registrados</h2><p>Se muestran por moneda. No se mezclan PEN y USD.</p><h3>Reservas no canceladas</h3>{Object.entries(summary.data.bookedAmountByCurrency).map(([currency, total]) => <p key={currency}>{api.money(total, currency)}</p>)}{!Object.keys(summary.data.bookedAmountByCurrency).length && <p>Sin importes registrados.</p>}<h3>Pagos aprobados simulados</h3>{Object.entries(summary.data.paidAmountByCurrency).map(([currency, total]) => <p key={currency}>{api.money(total, currency)}</p>)}{!Object.keys(summary.data.paidAmountByCurrency).length && <p>Sin pagos registrados.</p>}</section></div></>}
    <section><h2>Propiedades y disponibilidad</h2>{properties.isPending ? <p role="status">Consultando propiedades…</p> : properties.isError ? <ErrorBox error={properties.error} retry={() => void properties.refetch()} /> : <>{!properties.data.items.length && <div className="ops-panel"><p>No hay propiedades en esta página.</p>{page > 0 && <button onClick={() => change(0)}>Ir a la primera página</button>}</div>}<div className="ops-grid">{properties.data.items.map(p => <article className="ops-panel" key={p.id}><h2>{p.title}</h2><p>{p.district}, {p.city} · {statusLabels[p.status]}</p><Link to={`${base(role)}/properties/${p.id}/calendar`}>Gestionar fechas #{p.id} →</Link></article>)}</div><Pagination page={page} pages={properties.data.pages} change={change} busy={properties.isFetching} /></>}</section>
  </>
}
