CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    description VARCHAR(255),
    CONSTRAINT role_code_valid CHECK (code IN ('ADMINISTRATOR', 'SUPPORT', 'HOST', 'GUEST'))
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES roles(id),
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT user_email_normalized CHECK (email = lower(trim(email)))
);

CREATE INDEX users_role_idx ON users(role_id);
CREATE INDEX users_name_idx ON users(last_name, first_name);

INSERT INTO roles(code, description) VALUES
('ADMINISTRATOR', 'Administrator'),
('SUPPORT', 'Support'),
('HOST', 'Host'),
('GUEST', 'Guest');
