BEGIN;
CREATE TABLE IF NOT EXISTS properties (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id bigint NOT NULL REFERENCES users(id),
    title varchar(150) NOT NULL,
    description text NOT NULL,
    type varchar(50) NOT NULL,
    address varchar(255) NOT NULL,
    city varchar(100) NOT NULL,
    district varchar(100) NOT NULL,
    capacity integer NOT NULL CHECK (capacity > 0),
    bedrooms integer NOT NULL CHECK (bedrooms >= 0),
    beds integer NOT NULL CHECK (beds > 0),
    bathrooms integer NOT NULL CHECK (bathrooms >= 0),
    nightly_rate numeric(12,2) NOT NULL CHECK (nightly_rate > 0),
    currency varchar(3) NOT NULL DEFAULT 'PEN',
    status varchar(30) NOT NULL DEFAULT 'DRAFT',
    registration_key uuid NOT NULL DEFAULT gen_random_uuid(),
    submitted_at timestamptz,
    published_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    version bigint NOT NULL DEFAULT 0
);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS registration_key uuid NOT NULL DEFAULT gen_random_uuid();
CREATE UNIQUE INDEX IF NOT EXISTS properties_host_registration_key ON properties(host_id, registration_key);
CREATE INDEX IF NOT EXISTS properties_host_status_idx ON properties(host_id, status);
CREATE INDEX IF NOT EXISTS properties_status_location_idx ON properties(status, city, district);
COMMIT;
