BEGIN;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS published_at timestamptz;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS reviewed_at timestamptz;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS review_comment varchar(1000);
CREATE TABLE IF NOT EXISTS property_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id bigint NOT NULL REFERENCES properties(id),
    administrator_id bigint NOT NULL REFERENCES users(id),
    decision varchar(20) NOT NULL CHECK (decision IN ('APPROVED', 'REJECTED')),
    comment varchar(1000),
    property_version bigint NOT NULL,
    reviewed_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT property_reviews_property_version UNIQUE (property_id, property_version)
);
CREATE INDEX IF NOT EXISTS property_reviews_administrator_idx ON property_reviews(administrator_id);
COMMIT;
