BEGIN;
CREATE TABLE IF NOT EXISTS availability_blocks (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 property_id bigint NOT NULL REFERENCES properties(id), created_by_id bigint NOT NULL REFERENCES users(id),
 start_date date NOT NULL, end_date date NOT NULL, reason varchar(255) NOT NULL, active boolean NOT NULL DEFAULT true,
 deactivated_by_id bigint REFERENCES users(id), deactivated_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), version bigint NOT NULL DEFAULT 0,
 CONSTRAINT block_dates_valid CHECK(end_date>start_date)
);
CREATE TABLE IF NOT EXISTS bookings (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, confirmation_code uuid NOT NULL UNIQUE,
 property_id bigint NOT NULL REFERENCES properties(id), guest_id bigint NOT NULL REFERENCES users(id),
 check_in date NOT NULL, check_out date NOT NULL, guest_count integer NOT NULL CHECK(guest_count>0),
 applied_nightly_rate numeric(12,2) NOT NULL CHECK(applied_nightly_rate>0), total_amount numeric(12,2) NOT NULL CHECK(total_amount>0),
 currency varchar(3) NOT NULL, status varchar(20) NOT NULL,
 registration_key uuid NOT NULL, quoted_property_version bigint NOT NULL,
 confirmed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), version bigint NOT NULL DEFAULT 0,
 CONSTRAINT bookings_guest_registration_key UNIQUE(guest_id,registration_key),
 CONSTRAINT booking_dates_valid CHECK(check_out>check_in),
 CONSTRAINT booking_total_valid CHECK(total_amount=applied_nightly_rate*(check_out-check_in))
);
-- Compatible with an existing ERD schema whose bookings predate idempotent registration.
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS registration_key uuid NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS quoted_property_version bigint NOT NULL DEFAULT 0;
CREATE UNIQUE INDEX IF NOT EXISTS bookings_guest_registration_key ON bookings(guest_id,registration_key);
CREATE TABLE IF NOT EXISTS booking_status_history (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id bigint NOT NULL REFERENCES bookings(id), changed_by_id bigint NOT NULL REFERENCES users(id),
 previous_status varchar(20), new_status varchar(20) NOT NULL, comment varchar(1000), changed_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS simulated_payments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, booking_id bigint NOT NULL UNIQUE REFERENCES bookings(id), reference uuid NOT NULL UNIQUE,
 status varchar(20) NOT NULL, processed_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), version bigint NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS bookings_property_dates_idx ON bookings(property_id,status,check_in,check_out);
CREATE INDEX IF NOT EXISTS bookings_guest_created_idx ON bookings(guest_id,created_at);
CREATE INDEX IF NOT EXISTS availability_blocks_property_dates_idx ON availability_blocks(property_id,active,start_date,end_date);
CREATE INDEX IF NOT EXISTS booking_status_history_booking_idx ON booking_status_history(booking_id,changed_at);
CREATE INDEX IF NOT EXISTS simulated_payments_status_idx ON simulated_payments(status,created_at);
COMMIT;
